services:
  redis:
    build: .
    container_name: backgammon-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - backgammon-network

volumes:
  redis_data:
    driver: local

networks:
  backgammon-network:
    driver: bridge
